name: mlgiddetect-gpu
channels:
  - conda-forge
  - nvidia/label/cuda-12.9.1
dependencies:  
  - python=3.9
  - numpy<2
  - pip
  - onnxruntime
  - pytorch
  - torchvision
  - ffmpeg=4.3.2
  - cudnn=8.8.0.121
  - numpy<2
  - libcudnn
  - libstdcxx-ng
  - cuda-runtime
  - cupy

  - pip:
    - -e ../